#FROM tensorflow/tensorflow:latest-gpu
FROM python:3.9-slim
COPY . /srv/restberta-core
WORKDIR /srv/restberta-core

RUN mkdir /cache
RUN mkdir /cache/hf && \
    chmod a+rwx -R /cache/hf

ENV TRANSFORMERS_CACHE=/cache/hf \
    HUGGINGFACE_HUB_CACHE=${TRANSFORMERS_CACHE} \
    HF_HOME=${TRANSFORMERS_CACHE}

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install curl && apt-get -y install gpg

RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
     tee /etc/apt/sources.list.d/nvidia-container-toolkit.list \
  && \
    apt-get update

RUN apt-get install -y nvidia-container-toolkit

RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential

RUN pip install -r requirements.txt --src /usr/local/src

COPY nginx.conf /etc/nginx
RUN chmod +x ./start.sh
CMD ["./start.sh"]


